version: "3"

services:
  app:
    build: .
    restart: unless-stopped
    entrypoint: ["java", "-jar", "/app.jar"]
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db:5432
      DB_DATABASE: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres

  db:
    image: postgres:alpine
    restart: unless-stopped
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres